---
# tasks file for ansible.archyay
- name: Pexpect
  pip:
    name: pexpect

- name: Clone yay
  git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: "{{ srcdir }}/yay"
    update: true

- name: Build and install yay
  expect:
    chdir: "{{ srcdir }}/yay"
    command: "makepkg -sfi --noconfirm"
    creates: /usr/bin/yay
    responses:
      (?i)password: "{{ pass }}"

- name: Create the `wexder` user
  become: true
  ansible.builtin.user:
    name: wexder
    create_home: yes
    group: wheel

- name: Allow the `wexder` user to run `sudo pacman` without a password
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-install-wexder
    line: 'wexder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
