---
# tasks file for ansible.archyay
- name: Pexpect
  pip:
    name: pexpect

- name: Clone yay
  git:
    repo: https://aur.archlinux.org/yay-bin.git
    dest: "{{ srcdir }}/yay"
    update: true

- name: Build and install yay
  expect:
    chdir: "{{ srcdir }}/yay"
    command: "makepkg -sfi --noconfirm"
    creates: /usr/bin/yay
    responses:
      (?i)password: "{{ pass }}"
