---
- name: Install audio
  hosts: arch
  remote_user: wexder
  roles:
    - role: audio
- name: Install nvidia
  hosts: nvidia
  remote_user: wexder
  roles:
    - role: nvidia
- name: Install sway
  hosts: sway
  remote_user: wexder
  roles:
    - role: sway
    - role: desktopApps
- name: Install hyprland
  hosts: hyprland:&nvidia
  remote_user: wexder
  roles:
    - role: hypr
      nvidia: true
    - role: desktopApps
- name: Install hyprland
  hosts: hyprland
  remote_user: wexder
  roles:
    - role: hypr
      nvidia: false
    - role: desktopApps
- name: Install qemu
  hosts: qemu
  remote_user: wexder
  roles:
    - role: qemu
