---
- name: Base dev tools
  hosts: arch
  remote_user: wexder
  vars_prompt:
  - name: sudo_pass 
    prompt: Enter password
    private: true
  roles:
    - role: dev
    - role: nvim
    - role: terminal
      pass: "{{ sudo_pass }}"
