---
- name: Install essential desktop apps
  become_user: wexder
  become: true
  kewlfft.aur.aur:
    name:
      - alacritty
      - firefox
      - slack-desktop-wayland
      - caprine
      - blueberry-wayland
      - spotify
      - catppuccin-gtk-theme-mocha
      - wallutils
      - swaybg
      - synergy-git
      - postman-bin
      - thunar
      - dbeaver
      - wayvnc
      - yubioath-desktop

- name: Install my dotFiles config
  ansible.builtin.git:
    repo: "git@github.com:wexder/dotFiles"
    dest: ~/.config/dotFiles/

- name: Create a symbolic link for zshrc
  ansible.builtin.file:
    src: ~/.config/dotFiles/alacritty
    dest: ~/.config/alacritty
    owner: wexder
    state: link

- name: Create a symbolic link for gtk3
  ansible.builtin.file:
    src: ~/.config/dotFiles/gtk-3.0
    dest: ~/.config/gtk-3.0
    owner: wexder
    state: link

- name: Create a symbolic link for gtk4
  ansible.builtin.file:
    src: ~/.config/dotFiles/gtk-4.0
    dest: ~/.config/gtk-4.0
    owner: wexder
    state: link

- name: Start pcscd service
  become: true
  service:
    name: pcscd
    state: started
    enabled: true
