---
- name: Install essential desktop apps
  become_user: wexder
  become: true
  kewlfft.aur.aur:
    name:
      - alacritty
      - firefox
      - slack
      - caprine
      - rofi
      - wofi
      - blueberry
