---
- name: Install essential desktop apps
  become_user: wexder
  become: true
  kewlfft.aur.aur:
    name:
      - alacritty
      - firefox
      - slack-desktop-wayland
      - caprine
      - blueberry-wayland
      - spotify
      - catppuccin-gtk-theme-mocha
      - wallutils
      - swaybg
      - synergy-git
      - postman-bin

- name: Install my dotFiles config
  ansible.builtin.git:
    repo: "git@github.com:wexder/dotFiles"
    dest: ~/.config/dotFiles/

- name: Create a symbolic link for zshrc
  ansible.builtin.file:
    src: ~/.config/dotFiles/alacritty
    dest: ~/.config/alacritty
    owner: wexder
    state: link
