---
- name: Install pipewire
  become_user: aur_builder
  become: true
  kewlfft.aur.aur:
    name:
      - pipewire

- name: Install pipewire dependencies
  become_user: aur_builder
  become: true
  kewlfft.aur.aur:
    name:
      - pipewire-audio
      - pipewire-alsa
