---
- name: Install Wayland tools
  become_user: wexder
  become: true
  kewlfft.aur.aur:
    name:
      - xorg-xwayland 
      - wdisplays
      - wlr-randr
      - mako
      - kanshi
      - wl-clipboard
      - cliphist
      - wofi
      - networkmanager
      - wofi-wifi-menu-git
      - swaylock
      - swayidle
      - polkit
      - cronie
      - grim
      - swappy
      - slurp

- name: Install my dotFiles config
  ansible.builtin.git:
    repo: "git@github.com:wexder/dotFiles"
    dest: ~/.config/dotFiles/

- name: Create a symbolic link for wofi config
  ansible.builtin.file:
    src: ~/.config/dotFiles/wofi
    dest: ~/.config/wofi
    state: link

- name: Create a symbolic link for mako config
  ansible.builtin.file:
    src: ~/.config/dotFiles/mako
    dest: ~/.config/mako
    state: link

- name: Start networkmanager service
  service:
    name: NetworkManager
    enabled: true

- name: Create Pictures if not exists
  ansible.builtin.file:
    path: ~/Pictures
    state: directory

- name: Create a symbolic link for wallpapers config
  ansible.builtin.file:
    src: ~/.config/dotFiles/wallpapers
    dest: ~/Pictures/wallpapers
    state: link

- name: Random wallpaper every 10m
  ansible.builtin.cron:
    name: "Random wallpaper"
    minute: "*/10"
    job: "setrandom ~/Pictures/wallpapers"
