---
- name: Install Hyprland
  become_user: aur_builder
  become: true
  kewlfft.aur.aur:
    name:
      - hyprland-nvidia
  when: not nvidia

- name: Install Hyprland nvidia
  become_user: aur_builder
  become: true
  kewlfft.aur.aur:
    name:
      - hyprland-nvidia
  when: nvidia

- name: Install Hyprland tools
  become_user: aur_builder
  become: true
  kewlfft.aur.aur:
    name:
      - hyprland-nvidia
      - xdg-desktop-portal-hyprland-git
      - polkit
      - swaylock
      - swayidle

- name: Install my dotFiles config
  ansible.builtin.git:
    repo: "https://github.com/wexder/dotFiles"
    dest: ~/.config/dotFiles/

- name: Create a symbolic link for sway config
  ansible.builtin.file:
    src: ~/.config/dotFiles/hypr
    dest: ~/.config/hypr
    state: link

- name: Install waybar
  become_user: aur_builder
  become: true
  kewlfft.aur.aur:
    name:
      - waybar-hyprland-git

- name: Install my dotFiles config
  ansible.builtin.git:
    repo: "https://github.com/wexder/dotFiles"
    dest: ~/.config/dotFiles/

- name: Create a symbolic link for waybar config
  ansible.builtin.file:
    src: ~/.config/dotFiles/waybar
    dest: ~/.config/waybar
    owner: wexder
    state: link
