---
- name: Install sway tools
  become_user: wexder
  become: true
  kewlfft.aur.aur:
    name:
      - sway
      - xdg-desktop-portal
      - xdg-desktop-portal-wlr

- name: Install remove gnome portal if present 
  become: true
  ansible.builtin.pacman:
    name: "xdg-desktop-portal-gnome"
    state: absent

- name: Install remove gtk portal if present 
  become: true
  ansible.builtin.pacman:
    name: "xdg-desktop-portal-gtk"
    state: absent

- name: Install my dotFiles config
  ansible.builtin.git:
    repo: "git@github.com:wexder/dotFiles"
    dest: ~/.config/dotFiles/

- name: Create a symbolic link for sway config
  ansible.builtin.file:
    src: ~/.config/dotFiles/sway
    dest: ~/.config/sway
    state: link

- name: Install waybar
  become_user: wexder
  become: true
  kewlfft.aur.aur:
    name:
      - waybar

- name: Install my dotFiles config
  ansible.builtin.git:
    repo: "git@github.com:wexder/dotFiles"
    dest: ~/.config/dotFiles/

- name: Create a symbolic link for waybar config
  ansible.builtin.file:
    src: ~/.config/dotFiles/waybar
    dest: ~/.config/waybar
    owner: wexder
    state: link
